void add_history() {}
void add_history_time() {}
void alloc_history_entry() {}
void alphabetic() {}
void append_history() {}
void clear_history() {}
void completion_matches() {}
void copy_history_entry() {}
void crlf() {}
void current_history() {}
void ding() {}
int emacs_ctlx_keymap;
int emacs_meta_keymap;
int emacs_standard_keymap;
void filename_completion_function() {}
void free_history_entry() {}
void free_undo_list() {}
const void *funmap;
const void *funmap_program_specific_entry_start;
void get_history_event() {}
void history_arg_extract() {}
int history_base;
const void *history_comment_char;
void history_expand() {}
int history_expansion_char;
int history_file_version;
void history_get() {}
void history_get_history_state() {}
void history_get_time() {}
const void *history_inhibit_expansion_function;
void history_is_stifled() {}
const void *history_length;
const void *history_lines_read_from_file;
const void *history_lines_written_to_file;
void history_list() {}
const void *history_max_entries;
const void *history_multiline_entries;
int history_no_expand_chars;
const void *history_offset;
const void *history_quotes_inhibit_expansion;
const void *history_quoting_state;
void history_search() {}
const void *history_search_delimiter_chars;
void history_search_pos() {}
void history_search_prefix() {}
void history_set_history_state() {}
void history_set_pos() {}
int history_subst_char;
void history_tokenize() {}
void history_total_bytes() {}
void history_truncate_file() {}
int history_word_delimiters;
const void *history_write_timestamps;
void _hs_append_history_line() {}
void _hs_history_patsearch() {}
void _hs_replace_history_data() {}
const void *max_input_history;
void maybe_replace_line() {}
void maybe_save_line() {}
void maybe_unsave_line() {}
void next_history() {}
void previous_history() {}
void read_history() {}
void read_history_range() {}
void readline() {}
void readline_internal_char() {}
void readline_internal_setup() {}
void readline_internal_teardown() {}
void remove_history() {}
void remove_history_range() {}
void replace_history_entry() {}
void rl_abort() {}
void _rl_abort_internal() {}
void rl_activate_mark() {}
void rl_add_defun() {}
void _rl_add_executing_keyseq() {}
void rl_add_funmap_entry() {}
void _rl_add_macro_char() {}
void rl_add_undo() {}
void _rl_adjust_point() {}
const void *_rl_allow_pathname_alphabetic_chars;
void rl_alphabetic() {}
const void *rl_already_prompted;
void _rl_any_typein() {}
void _rl_arg_callback() {}
const void *_rl_argcxt;
void _rl_arg_dispatch() {}
void _rl_arg_getchar() {}
void _rl_arg_init() {}
void _rl_arg_overflow() {}
int rl_arg_sign;
void rl_arrow_keys() {}
const void *rl_attempted_completion_function;
const void *rl_attempted_completion_over;
void _rl_backspace() {}
void rl_backward() {}
void rl_backward_byte() {}
void rl_backward_char() {}
void _rl_backward_char_internal() {}
void rl_backward_char_search() {}
void rl_backward_kill_line() {}
void rl_backward_kill_word() {}
void rl_backward_menu_complete() {}
void rl_backward_word() {}
int rl_basic_quote_characters;
int rl_basic_word_break_characters;
void rl_beginning_of_history() {}
void rl_begin_undo_group() {}
void rl_beg_of_line() {}
int _rl_bell_preference;
const void *rl_binding_keymap;
void rl_bind_key() {}
void rl_bind_key_if_unbound() {}
void rl_bind_key_if_unbound_in_map() {}
void rl_bind_key_in_map() {}
void rl_bind_keyseq() {}
void rl_bind_keyseq_if_unbound() {}
void rl_bind_keyseq_if_unbound_in_map() {}
void rl_bind_keyseq_in_map() {}
int _rl_bind_stty_chars;
const void *rl_blink_matching_paren;
void _rl_block_sigint() {}
void _rl_block_sigwinch() {}
void rl_bracketed_paste_begin() {}
void _rl_bracketed_read_key() {}
void _rl_bracketed_read_mbstring() {}
void _rl_bracketed_text() {}
const void *rl_byte_oriented;
const void *_rl_callback_data;
void _rl_callback_data_alloc() {}
void _rl_callback_data_dispose() {}
const void *_rl_callback_func;
void rl_callback_handler_install() {}
void rl_callback_handler_remove() {}
void rl_callback_read_char() {}
void rl_callback_sigcleanup() {}
void rl_call_last_kbd_macro() {}
void rl_capitalize_word() {}
int rl_catch_signals;
int rl_catch_sigwinch;
const void *_rl_caught_signal;
int rl_change_environment;
void rl_character_len() {}
const void *rl_char_is_quoted_p;
void rl_char_search() {}
void _rl_char_search_internal() {}
void _rl_char_value() {}
void rl_check_signals() {}
void rl_cleanup_after_signal() {}
void _rl_clean_up_for_exit() {}
void rl_clear_display() {}
void rl_clear_history() {}
void rl_clear_message() {}
void rl_clear_pending_input() {}
void _rl_clear_screen() {}
void rl_clear_screen() {}
void rl_clear_signals() {}
void _rl_clear_to_eol() {}
void rl_clear_visible_line() {}
const void *_rl_colored_completion_prefix;
const void *_rl_colored_stats;
const void *_rl_color_ext_list;
int _rl_color_indicator;
const void *_rl_command_to_execute;
const void *_rl_comment_begin;
void _rl_compare_chars() {}
void rl_complete() {}
void rl_complete_internal() {}
int _rl_complete_mark_directories;
const void *_rl_complete_mark_symlink_dirs;
const void *rl_completer_quote_characters;
const void *rl_completer_word_break_characters;
const void *_rl_complete_show_all;
const void *_rl_complete_show_unmodified;
const void *rl_complete_with_tilde_expansion;
int rl_completion_append_character;
const void *_rl_completion_case_fold;
const void *_rl_completion_case_map;
int _rl_completion_columns;
const void *rl_completion_display_matches_hook;
const void *rl_completion_entry_function;
const void *rl_completion_found_quote;
const void *rl_completion_invoking_key;
const void *rl_completion_mark_symlink_dirs;
void rl_completion_matches() {}
void rl_completion_mode() {}
const void *_rl_completion_prefix_display_length;
int rl_completion_query_items;
const void *rl_completion_quote_character;
const void *rl_completion_suppress_append;
const void *rl_completion_suppress_quote;
const void *rl_completion_type;
const void *rl_completion_word_break_hook;
void _rl_control_keypad() {}
int _rl_convert_meta_chars_to_ascii;
void rl_copy_backward_word() {}
void rl_copy_forward_word() {}
void rl_copy_keymap() {}
void rl_copy_region_to_kill() {}
void rl_copy_text() {}
void _rl_copy_undo_entry() {}
void _rl_copy_undo_list() {}
void _rl_cr() {}
void rl_crlf() {}
void _rl_current_display_line() {}
void rl_deactivate_mark() {}
void rl_delete() {}
void rl_delete_horizontal_space() {}
void rl_delete_or_show_completions() {}
void rl_delete_text() {}
int rl_deprep_term_function;
void rl_deprep_terminal() {}
void rl_digit_argument() {}
void _rl_digit_p() {}
void _rl_digit_value() {}
void rl_ding() {}
const void *rl_directory_completion_hook;
const void *rl_directory_rewrite_hook;
void _rl_disable_meta_key() {}
void _rl_disable_tty_signals() {}
void rl_discard_argument() {}
void rl_discard_keymap() {}
void _rl_dispatch() {}
void _rl_dispatch_callback() {}
const void *rl_dispatching;
const void *_rl_dispatching_keymap;
void _rl_dispatch_subseq() {}
const void *rl_display_fixed;
void rl_display_match_list() {}
const void *rl_display_prompt;
const void *_rl_doing_an_undo;
void rl_do_lowercase_version() {}
const void *rl_done;
void rl_do_undo() {}
void rl_downcase_word() {}
void rl_dump_functions() {}
void rl_dump_macros() {}
void rl_dump_variables() {}
int _rl_echo_control_chars;
const void *_rl_echoctl;
const void *_rl_echoing_p;
void rl_echo_signal_char() {}
int rl_editing_mode;
void rl_emacs_editing_mode() {}
const void *_rl_emacs_mode_str;
const void *_rl_emacs_modestr_len;
void rl_empty_keymap() {}
int _rl_enable_active_region;
int _rl_enable_bracketed_paste;
const void *_rl_enable_keypad;
int _rl_enable_meta;
void _rl_enable_meta_key() {}
void _rl_enable_paren_matching() {}
const void *rl_end;
void _rl_end_executing_keyseq() {}
void rl_end_kbd_macro() {}
void rl_end_of_history() {}
void rl_end_of_line() {}
void rl_end_undo_group() {}
int _rl_eof_char;
const void *_rl_eof_found;
void _rl_erase_at_end_of_line() {}
const void *rl_erase_empty_line;
void _rl_erase_entire_line() {}
void _rl_errmsg() {}
const void *rl_event_hook;
void rl_exchange_point_and_mark() {}
void rl_execute_next() {}
const void *rl_executing_key;
const void *rl_executing_keymap;
const void *rl_executing_keyseq;
const void *_rl_executing_keyseq_size;
const void *rl_executing_macro;
void rl_expand_prompt() {}
const void *rl_explicit_arg;
void rl_extend_line_buffer() {}
const void *rl_filename_completion_desired;
void rl_filename_completion_function() {}
const void *rl_filename_dequoting_function;
const void *rl_filename_quote_characters;
int rl_filename_quoting_desired;
int rl_filename_quoting_function;
const void *rl_filename_rewrite_hook;
const void *rl_filename_stat_hook;
void _rl_find_completion_word() {}
void _rl_find_next_mbchar() {}
void _rl_find_prev_mbchar() {}
void _rl_find_prev_mbchar_internal() {}
void _rl_fix_last_undo_of_type() {}
void _rl_fix_mark() {}
void _rl_fix_point() {}
void rl_forced_update_display() {}
void rl_forward() {}
void rl_forward_byte() {}
void rl_forward_char() {}
void _rl_forward_char_internal() {}
void rl_forward_search_history() {}
void rl_forward_word() {}
void rl_free() {}
void _rl_free_history_entry() {}
void rl_free_keymap() {}
void rl_free_line_state() {}
void _rl_free_match_list() {}
void _rl_free_saved_history_line() {}
void _rl_free_undo_list() {}
void rl_free_undo_list() {}
void rl_function_dumper() {}
void rl_function_of_keyseq() {}
void rl_function_of_keyseq_len() {}
void rl_funmap_names() {}
void rl_generic_bind() {}
void rl_getc() {}
int rl_getc_function;
void _rl_get_char_len() {}
void rl_get_keymap() {}
void rl_get_keymap_by_name() {}
void rl_get_keymap_name() {}
void rl_get_keymap_name_from_edit_mode() {}
void rl_get_next_history() {}
void rl_get_previous_history() {}
void _rl_get_screen_size() {}
void rl_get_screen_size() {}
void rl_get_termcap() {}
int rl_gnu_readline_p;
const void *_rl_history_preserve_point;
int _rl_history_saved_point;
void rl_history_search_backward() {}
void rl_history_search_forward() {}
void rl_history_substr_search_backward() {}
void rl_history_substr_search_forward() {}
const void *_rl_horizontal_scroll_mode;
int rl_ignore_completion_duplicates;
const void *rl_ignore_some_completions_function;
const void *rl_inhibit_completion;
void _rl_init_eightbit() {}
void _rl_init_executing_keyseq() {}
void rl_initialize() {}
void rl_initialize_funmap() {}
void _rl_init_line_state() {}
void _rl_init_locale() {}
void _rl_init_terminal_io() {}
void _rl_input_available() {}
const void *rl_input_available_hook;
void _rl_input_queued() {}
void rl_insert() {}
void _rl_insert_char() {}
void rl_insert_close() {}
void rl_insert_comment() {}
void rl_insert_completions() {}
int rl_insert_mode;
void rl_insert_text() {}
void _rl_insert_typein() {}
const void *_rl_in_stream;
const void *rl_instream;
void _rl_internal_char_cleanup() {}
const void *_rl_internal_startup_hook;
const void *_rl_intr_char;
void rl_invoking_keyseqs() {}
void rl_invoking_keyseqs_in_map() {}
const void *_rl_iscxt;
void _rl_isearch_callback() {}
void _rl_isearch_cleanup() {}
void _rl_isearch_dispatch() {}
const void *_rl_isearch_terminators;
void _rl_is_mbchar_matched() {}
const void *_rl_keep_mark_active;
void rl_keep_mark_active() {}
int _rl_keymap;
void _rl_keyseq_chain_dispose() {}
void _rl_keyseq_cxt_alloc() {}
void _rl_keyseq_cxt_dispose() {}
int _rl_keyseq_timeout;
const void *rl_key_sequence_length;
void rl_kill_full_line() {}
void _rl_kill_kbd_macro() {}
void rl_kill_line() {}
void rl_kill_region() {}
void rl_kill_text() {}
void rl_kill_word() {}
const void *_rl_kscxt;
const void *_rl_last_command_was_kill;
const void *_rl_last_c_pos;
const void *rl_last_func;
const void *_rl_last_v_pos;
int rl_library_version;
const void *rl_line_buffer;
const void *rl_line_buffer_len;
const void *rl_linefunc;
void rl_list_funmap_names() {}
void _rl_lowercase_p() {}
void rl_macro_bind() {}
void rl_macro_dumper() {}
void rl_make_bare_keymap() {}
void rl_make_keymap() {}
void _rl_make_prompt_for_search() {}
const void *rl_mark;
void rl_mark_active_p() {}
const void *_rl_mark_modified_lines;
int _rl_match_hidden_files;
void rl_maybe_replace_line() {}
void rl_maybe_save_line() {}
void rl_maybe_unsave_line() {}
void rl_menu_complete() {}
const void *_rl_menu_complete_prefix_first;
const void *rl_menu_completion_entry_function;
void rl_message() {}
const void *_rl_meta_flag;
void rl_modifying() {}
void _rl_move_vert() {}
void rl_named_function() {}
void _rl_nchars_available() {}
void rl_newline() {}
void _rl_next_macro_key() {}
void rl_next_screen_line() {}
void rl_noninc_forward_search() {}
void rl_noninc_forward_search_again() {}
void rl_noninc_reverse_search() {}
void rl_noninc_reverse_search_again() {}
const void *_rl_nscxt;
void _rl_nsearch_callback() {}
void _rl_nsearch_cleanup() {}
void _rl_null_function() {}
const void *rl_num_chars_to_read;
int rl_numeric_arg;
void rl_old_menu_complete() {}
void rl_on_new_line() {}
void rl_on_new_line_with_prompt() {}
void rl_operate_and_get_next() {}
void _rl_optimize_redisplay() {}
int _rl_optimize_typeahead;
const void *_rl_orig_sigset;
void _rl_output_character_function() {}
const void *_rl_output_meta_chars;
void _rl_output_some_chars() {}
const void *_rl_out_stream;
const void *rl_outstream;
void _rl_overwrite_char() {}
void rl_overwrite_mode() {}
void _rl_overwrite_rubout() {}
int _rl_page_completions;
void rl_parse_and_bind() {}
void _rl_parse_colors() {}
const void *_rl_parsing_conditionalized_out;
void _rl_peek_macro_key() {}
const void *_rl_pending_command;
const void *rl_pending_input;
void rl_pending_signal() {}
const void *rl_persistent_signal_handlers;
const void *rl_point;
void _rl_pop_executing_macro() {}
void rl_possible_completions() {}
int _rl_possible_control_prefixes;
int _rl_possible_meta_prefixes;
const void *rl_prefer_env_winsize;
const void *rl_pre_input_hook;
void _rl_prep_non_filename_text() {}
int rl_prep_term_function;
void rl_prep_terminal() {}
void rl_previous_screen_line() {}
void _rl_prev_macro_key() {}
void _rl_print_color_indicator() {}
const void *_rl_print_completions_horizontally;
void rl_print_last_kbd_macro() {}
void _rl_print_prefix_color() {}
const void *rl_prompt;
void _rl_pure_alphabetic() {}
void _rl_pushed_input_available() {}
void _rl_push_executing_macro() {}
void rl_push_macro_input() {}
void _rl_put_indicator() {}
void _rl_qsort_string_compare() {}
const void *_rl_quit_char;
void rl_quoted_insert() {}
void _rl_read_bracketed_paste_prefix() {}
void rl_read_init_file() {}
void rl_read_key() {}
int rl_readline_name;
const void *rl_readline_state;
int rl_readline_version;
void _rl_read_mbchar() {}
void _rl_read_mbstring() {}
void rl_redisplay() {}
void _rl_redisplay_after_sigwinch() {}
int rl_redisplay_function;
void rl_redraw_prompt_last_line() {}
void _rl_refresh_line() {}
void rl_refresh_line() {}
void _rl_release_sigint() {}
void _rl_release_sigwinch() {}
void rl_replace_from_history() {}
void rl_replace_line() {}
void _rl_replace_text() {}
void rl_re_read_init_file() {}
void rl_reset_after_signal() {}
void _rl_reset_argument() {}
void _rl_reset_completion_state() {}
void rl_reset_line_state() {}
void _rl_reset_prompt() {}
void rl_reset_screen_size() {}
void rl_reset_terminal() {}
void rl_resize_terminal() {}
void rl_restart_output() {}
void rl_restore_prompt() {}
void rl_restore_state() {}
void _rl_restore_tty_signals() {}
void rl_reverse_search_history() {}
const void *_rl_revert_all_at_newline;
void _rl_revert_all_lines() {}
void rl_revert_line() {}
void _rl_revert_previous_lines() {}
void rl_rubout() {}
void _rl_rubout_char() {}
void rl_rubout_or_delete() {}
const void *_rl_saved_line_for_history;
void rl_save_prompt() {}
void rl_save_state() {}
void _rl_savestring() {}
const void *_rl_screenchars;
const void *_rl_screenheight;
const void *_rl_screenwidth;
void _rl_scxt_alloc() {}
void _rl_scxt_dispose() {}
void _rl_search_getchar() {}
void _rl_set_cursor() {}
void _rl_set_insert_mode() {}
void rl_set_key() {}
void rl_set_keyboard_input_timeout() {}
void rl_set_keymap() {}
void rl_set_keymap_from_edit_mode() {}
void rl_set_keymap_name() {}
void rl_set_mark() {}
void _rl_set_mark_at_pos() {}
void _rl_set_normal_color() {}
void rl_set_paren_blink_timeout() {}
void rl_set_prompt() {}
void rl_set_retained_kills() {}
void _rl_set_screen_size() {}
void rl_set_screen_size() {}
void rl_set_signals() {}
void _rl_set_the_line() {}
void rl_show_char() {}
const void *_rl_show_mode_in_prompt;
const void *_rl_sigcleanarg;
const void *_rl_sigcleanup;
const void *rl_signal_event_hook;
void _rl_signal_handler() {}
void _rl_sigwinch_resize_terminal() {}
const void *_rl_skip_completed_text;
void rl_skip_csi_sequence() {}
int rl_sort_completion_matches;
const void *rl_special_prefixes;
void _rl_standout_off() {}
void _rl_standout_on() {}
void rl_start_kbd_macro() {}
const void *rl_startup_hook;
void _rl_start_using_history() {}
void rl_stop_output() {}
void _rl_strindex() {}
void _rl_strip_prompt() {}
void rl_stuff_char() {}
const void *_rl_suppress_redisplay;
const void *_rl_susp_char;
void rl_tab_insert() {}
int _rl_term_autowrap;
const void *_rl_term_backspace;
const void *_rl_term_clreol;
const void *_rl_term_clrpag;
const void *_rl_term_clrscroll;
const void *_rl_term_cr;
const void *_rl_term_dc;
const void *_rl_term_DC;
const void *_rl_term_ei;
void _rl_term_executing_keyseq() {}
const void *_rl_term_forward_char;
const void *_rl_term_goto;
const void *_rl_term_ic;
const void *_rl_term_IC;
const void *_rl_term_im;
const void *_rl_terminal_can_insert;
const void *rl_terminal_name;
const void *_rl_term_ip;
const void *_rl_term_pc;
const void *_rl_term_up;
void rl_tilde_expand() {}
void _rl_to_lower() {}
const void *_rl_top_level;
void _rl_to_upper() {}
void rl_translate_keyseq() {}
void rl_transpose_chars() {}
void rl_transpose_words() {}
void _rl_ttyflush() {}
void _rl_ttymsg() {}
void rl_tty_set_default_bindings() {}
void rltty_set_default_bindings() {}
void rl_tty_set_echoing() {}
void rl_tty_status() {}
void rl_tty_unset_default_bindings() {}
void rl_unbind_command_in_map() {}
void rl_unbind_function_in_map() {}
void rl_unbind_key() {}
void rl_unbind_key_in_map() {}
void rl_undo_command() {}
const void *_rl_undo_group_level;
const void *rl_undo_list;
void _rl_unget_char() {}
void rl_universal_argument() {}
void rl_unix_filename_rubout() {}
void rl_unix_line_discard() {}
void rl_unix_word_rubout() {}
void rl_untranslate_keyseq() {}
void _rl_untranslate_macro_value() {}
void rl_upcase_word() {}
void _rl_update_final() {}
void _rl_uppercase_p() {}
void rl_username_completion_function() {}
const void *_rl_utf8locale;
void rl_variable_bind() {}
void rl_variable_dumper() {}
void rl_variable_value() {}
void rl_vi_append_eol() {}
void rl_vi_append_mode() {}
void rl_vi_arg_digit() {}
void rl_vi_back_to_indent() {}
void rl_vi_bracktype() {}
void rl_vi_bword() {}
void rl_vi_bWord() {}
void rl_vi_change_case() {}
void rl_vi_change_char() {}
void rl_vi_change_to() {}
void rl_vi_char_search() {}
void rl_vi_check() {}
const void *_rl_vi_cmd_mode_str;
const void *_rl_vi_cmd_modestr_len;
void rl_vi_column() {}
void rl_vi_complete() {}
void rl_vi_delete() {}
void rl_vi_delete_to() {}
void rl_vi_domove() {}
void _rl_vi_domove_callback() {}
void _rl_vi_domove_motion_cleanup() {}
void _rl_vi_done_inserting() {}
void rl_vi_editing_mode() {}
void rl_vi_end_word() {}
void rl_vi_eof_maybe() {}
void rl_vi_eword() {}
void rl_vi_eWord() {}
void rl_vi_fetch_history() {}
void rl_vi_first_print() {}
void rl_vi_fword() {}
void rl_vi_fWord() {}
void rl_vi_goto_mark() {}
void _rl_vi_initialize_line() {}
void rl_vi_insert_beg() {}
void rl_vi_insertion_mode() {}
void rl_vi_insert_mode() {}
const void *_rl_vi_ins_mode_str;
const void *_rl_vi_ins_modestr_len;
int _rl_vi_last_command;
void rl_vi_match() {}
void _rl_vi_motion_command() {}
void rl_vi_movement_mode() {}
const void *_rl_vimvcxt;
void rl_vi_next_word() {}
void rl_vi_overstrike() {}
void rl_vi_overstrike_delete() {}
void rl_vi_prev_word() {}
void rl_vi_put() {}
void rl_vi_redo() {}
const void *_rl_vi_redoing;
void rl_vi_replace() {}
void _rl_vi_reset_last() {}
void rl_vi_rubout() {}
const void *_rl_vis_botlin;
void rl_vi_search() {}
void rl_vi_search_again() {}
void _rl_vi_set_last() {}
void rl_vi_set_mark() {}
const void *rl_visible_prompt_length;
const void *rl_visible_stats;
void rl_vi_start_inserting() {}
void rl_vi_subst() {}
void _rl_vi_textmod_command() {}
void rl_vi_tilde_expand() {}
void rl_vi_undo() {}
void rl_vi_unix_word_rubout() {}
void rl_vi_yank_arg() {}
void rl_vi_yank_pop() {}
void rl_vi_yank_to() {}
void _rl_walphabetic() {}
const void *_rl_want_redisplay;
void _rl_with_macro_input() {}
void rl_yank() {}
void rl_yank_last_arg() {}
void rl_yank_nth_arg() {}
void rl_yank_pop() {}
void sh_get_env_value() {}
void sh_get_home_dir() {}
void sh_set_lines_and_columns() {}
void sh_single_quote() {}
void sh_unset_nodelay_mode() {}
void stifle_history() {}
int tilde_additional_prefixes;
int tilde_additional_suffixes;
void tilde_expand() {}
void tilde_expand_word() {}
const void *tilde_expansion_failure_hook;
const void *tilde_expansion_preexpansion_hook;
void unstifle_history() {}
void username_completion_function() {}
void using_history() {}
int vi_insertion_keymap;
int vi_movement_keymap;
void where_history() {}
void write_history() {}
void xfree() {}
void xmalloc() {}
void xrealloc() {}
