void adler32() {}
void adler32_combine() {}
void adler32_combine64() {}
void adler32_z() {}
void compress() {}
void compress2() {}
void compressBound() {}
void crc32() {}
void crc32_combine() {}
void crc32_combine64() {}
void crc32_z() {}
void deflate() {}
void deflateBound() {}
void deflateCopy() {}
void deflateEnd() {}
void deflateGetDictionary() {}
void deflateInit_() {}
void deflateInit2_() {}
void deflateParams() {}
void deflatePending() {}
void deflatePrime() {}
void deflateReset() {}
void deflateResetKeep() {}
void deflateSetDictionary() {}
void deflateSetHeader() {}
void deflateTune() {}
void get_crc_table() {}
void gzbuffer() {}
void gzclearerr() {}
void gzclose() {}
void gzclose_r() {}
void gzclose_w() {}
void gzdirect() {}
void gzdopen() {}
void gzeof() {}
void gzerror() {}
void gzflush() {}
void gzfread() {}
void gzfwrite() {}
void gzgetc() {}
void gzgetc_() {}
void gzgets() {}
void gzoffset() {}
void gzoffset64() {}
void gzopen() {}
void gzopen64() {}
void gzprintf() {}
void gzputc() {}
void gzputs() {}
void gzread() {}
void gzrewind() {}
void gzseek() {}
void gzseek64() {}
void gzsetparams() {}
void gztell() {}
void gztell64() {}
void gzungetc() {}
void gzvprintf() {}
void gzwrite() {}
void inflate() {}
void inflateBack() {}
void inflateBackEnd() {}
void inflateBackInit_() {}
void inflateCodesUsed() {}
void inflateCopy() {}
void inflateEnd() {}
void inflateGetDictionary() {}
void inflateGetHeader() {}
void inflateInit_() {}
void inflateInit2_() {}
void inflateMark() {}
void inflatePrime() {}
void inflateReset() {}
void inflateReset2() {}
void inflateResetKeep() {}
void inflateSetDictionary() {}
void inflateSync() {}
void inflateSyncPoint() {}
void inflateUndermine() {}
void inflateValidate() {}
void uncompress() {}
void uncompress2() {}
void zError() {}
void zlibCompileFlags() {}
void zlibVersion() {}
