name: Check

on:
  push:
    branches: [ main ]

jobs:
  phoenixbuilder-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Build PhoenixBuilder
      run: make current
